my_new_project:
  target: prod
  outputs:
    prod:
      type: bigquery
      method: service-account-json
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: "{{ env_var('GCP_DATASET') }}"
      keyfile: "{{ env_var('GCP_SA_KEY') }}"
      threads: 4
      timeout_seconds: 300
      location: EU