name: dbt CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure GCP project
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Build Docker image
        run: |
          docker build -t ${GCP_REGION}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/mpetrovic-artifact-registry/dbt-runner:latest .

      - name: Push Docker image
        run: |
          docker push ${GCP_REGION}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/mpetrovic-artifact-registry/dbt-runner:latest

